function p = init_clean_param_record(class_id, sample_index)

p = struct( ...
    'class_id',      int32(class_id), ...
    'sample_index',  int32(sample_index), ...
    'A',             NaN, ...
    'phi',           NaN, ...
    'f0',            NaN, ...
    'f1',            NaN, ...
    'fc',            NaN, ...
    'df',            NaN, ...
    'fm',            NaN, ...
    'T',             NaN, ...
    'beta',          NaN, ...
    'kappa',         NaN, ...
    'K',             NaN, ...
    'fL',            NaN, ...
    'fH',            NaN, ...
    'bandwidth',     NaN, ...
    'bin_info',      struct(), ...
    'hop_info',      struct(), ...
    'lims',          struct(), ...
    'units',         struct() ...
);

end