function x_clean = synthesize_clean_signal_class11(params, spec)
% SYNTHESIZE_CLEAN_SIGNAL_CLASS11
% Chaotic FM Jammer
%
% The instantaneous frequency follows a deterministic chaotic trajectory
% generated by the logistic map. Integrating frequency to phase preserves
% temporal correlations in the output (non-zero bispectrum), which is the
% feature distinguishing this from any class 0-9 signal.
%
% Model:
%   y[n] = r * y[n-1] * (1 - y[n-1])           (logistic map, r in [3.92, 3.99])
%   f_inst[n] = f_dev * (2*y[n] - 1)           (map [0,1] -> [-f_dev, +f_dev])
%   phi_chaotic[n] = (2*pi/fs) * cumsum(f_inst[n])
%   x[n] = A * exp(j * (2*pi*fc*n/fs + phi_chaotic[n] + phi0))
%
% Field aliasing (kept for schema compatibility):
%   params.Rc    = logistic map parameter r
%   params.sigma = chaotic frequency deviation f_dev (Hz)
%   params.alpha = logistic map initial condition y0

    N  = double(spec.N);
    fs = double(spec.fs);
    t  = (0:N-1)' / fs;

    A    = params.A;
    fc   = params.fc;
    phi0 = params.phi;
    r       = params.Rc;
    f_dev   = params.sigma;
    y0      = params.alpha;

    % Generate logistic map sequence
    y = zeros(N, 1);
    y(1) = y0;
    for n = 2:N
        y(n) = r * y(n-1) * (1 - y(n-1));
    end

    % Map [0,1] -> [-f_dev, +f_dev]: chaotic instantaneous frequency
    f_inst = f_dev * (2*y - 1);

    % Integrate frequency to phase. cumsum/fs is the discrete-time integral.
    phi_chaotic = (2*pi/fs) * cumsum(f_inst);

    % Total instantaneous phase
    phase = 2*pi*fc*t + phi_chaotic + phi0;
    x = A * exp(1i * phase);

    % RMS normalize
    rms_val = sqrt(mean(abs(x).^2));
    assert(rms_val > 0, 'ChaoticFM: RMS is zero before normalization.');
    x_clean = x / rms_val;

    % Assertions
    assert(iscolumn(x_clean), 'Output must be a column vector.');
    assert(numel(x_clean) == spec.N, 'Output length mismatch.');
    assert(~isreal(x_clean), 'Signal must be complex.');
    assert(~all(imag(x_clean(:)) == 0), ...
        'Signal must have non-zero imaginary component.');
    assert(all(isfinite(x_clean(:))), 'Signal contains NaN/Inf.');
end