function p = init_imp_param_record()

p = struct( ...
    'impairment_seed', NaN, ...
    'target_snr_db', NaN, ...
    'realized_snr_db', NaN, ...
    'noise_variance', NaN, ...
    'P_signal', NaN, ...
    'P_noise_realized', NaN, ...
    'amp_scale', NaN, ...
    'phase_offset_rad', NaN, ...
    'normalization_rms', NaN ...
);

end